### Module 1

##### Task 1

In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('dataset.csv')

In [5]:
df.sample(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
489494,578017ä,ö21931^,JUMBO STORAGE BAG SUKI,1,2011-11-22 13:07:00,2.08,13569.0,United Kingdom
416637,572553,ö23170^,REGENCY TEA PLATE ROSES,4@,2011-10-24 17:09:00,Ww3.29,NaN,United Kingdom
222413,556427,ö21179^,NO JUNK MAIL METAL SIGN,1,2011-06-10 13:23:00,3.29,NaN,XxYUnited Kingdom☺️
280303,561391ä,22669,RED BABY BUNTING,5,2011-07-27 09:59:00,2.95,16628.0,XxYUnited Kingdom☺️
351086,567661,21248,DOOR HANGER MUM + DADS ROOM,1,2011-09-21 15:06:00,1.45,13959.0,United Kingdom
418503,572726,ö21485^,RETROSPOT HEART HOT WATER BOTTLE,1@,2011-10-25 15:19:00,4.95,16056.0,XxYUnited Kingdom☺️
325831,565457,ö22112^,CHOCOLATE HOT WATER BOTTLE,6,2011-09-05 09:07:00,Ww4.95,&14565.0#,XxYUnited Kingdom☺️
46940,540372,22984,$CARD GINGHAM ROSE,24@,2011-01-06 16:41:00,0.42,&13081.0#,United Kingdom
55297,540986,ö22505^,$MEMO BOARD COTTAGE DESIGN,4,2011-01-12 16:14:00,4.95,15291.0,United Kingdom
538218,581402,22309,$TEA COSY RED STRIPE,2,2011-12-08 13:45:00,2.55,14653.0,XxYUnited Kingdom☺️
101232,544908,22859,EASTER TIN BUNNY BOUQUET,6,2011-02-24 14:27:00,1.65,18056.0,XxYUnited Kingdom☺️
332275,566060ä,22697,GREEN REGENCY TEACUP AND SAUCER,2@,2011-09-08 15:27:00,5.79,NaN,XxYUnited Kingdom☺️
118925,546502,ö22654^,DELUXE SEWING KIT,1,2011-03-14 11:46:00,5.95,16005.0,United Kingdom
188074,553013ä,ö23348^,$CHILDRENS TOY COOKING UTENSIL SET,1@,2011-05-12 18:19:00,4.13,NaN,United Kingdom
369798,569100,ö84997D^,$CHILDRENS CUTLERY POLKADOT PINK,1,2011-09-30 12:19:00,4.15,12748.0,XxYUnited Kingdom☺️
104900,545215ä,84568,GIRLS ALPHABET IRON ON PATCHES,15@,2011-02-28 16:47:00,0.42,NaN,XxYUnited Kingdom☺️
225801,556733,ö48116^,$DOORMAT MULTICOLOUR STRIPE,2@,2011-06-14 11:53:00,Ww7.95,16919.0,XxYUnited Kingdom☺️
50852,540566,ö22354^,RETROSPOT PADDED SEAT CUSHION,2,2011-01-10 10:58:00,Ww3.75,17811.0,United Kingdom
139036,548259ä,ö22441^,$GROW YOUR OWN BASIL IN ENAMEL MUG,3@,2011-03-30 11:12:00,2.1,14099.0,XxYUnited Kingdom☺️
63749,541592ä,ö85017B^,ENVELOPE 50 BLOSSOM IMAGES,1,2011-01-19 15:08:00,Ww0.83,NaN,United Kingdom

In [6]:
df.duplicated().sum()

91

In [7]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1025
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     108000
Country             0
dtype: int64

In [8]:
df.size

4335272

In [9]:
import re

def remove_non_standard_characters(column):
    # regex for anything outside a-z, A-Z, 0-9
    pattern = re.compile(r'[^a-zA-Z0-9]')
    cleaned = pattern.sub('', column)
    return cleaned
df['InvoiceNo'] = df['InvoiceNo'].apply(remove_non_standard_characters)
df['StockCode'] = df['StockCode'].apply(remove_non_standard_characters)
df['Quantity'] = df['Quantity'].apply(remove_non_standard_characters)

In [10]:
def remove_non_numeric_characters(price):
    #regex for non-numeric characters and .
    pattern = re.compile(r'[^0-9.]')
    cleaned = pattern.sub('', price)
    return cleaned

df['UnitPrice'] = df['UnitPrice'].apply(remove_non_numeric_characters)

In [11]:
#removing 'XxY' & '☺️' from country
substrings_to_remove = ['XxY', '☺️']

for substring in substrings_to_remove:
    df['Country'] = df['Country'].str.replace(substring, '')

In [12]:
def remove_special_characters(customer_id):
    customer_id = str(customer_id)
    pattern = re.compile(r'[^a-zA-Z0-9]')
    cleaned_id = pattern.sub('', customer_id)
    return cleaned_id
df['CustomerID'] = df['CustomerID'].apply(remove_special_characters)

#replace string nan with NAN type
df['CustomerID'].replace('nan', np.nan, inplace=True)

In [13]:
#replace $ with emplty str
df['Description'] = df['Description'].str.replace('$', '')

C:\Users\Shedrack\AppData\Local\Temp\ipykernel_1528\516105303.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Description'] = df['Description'].str.replace('$', '')

In [14]:
df.sample(50)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
143014,548663,22171,3 HOOK PHOTO SHELF ANTIQUE WHITE,1,2011-04-01 14:44:00,16.63,NaN,United Kingdom
16002,537643,21157,RED RETROSPOT WASHBAG,4,2010-12-07 15:34:00,4.21,NaN,United Kingdom
241792,558240,23227,FILIGREE HEART BUTTERFLY WHITE,1,2011-06-27 15:27:00,2.46,NaN,United Kingdom
532309,580983,22361,GLASS JAR DAISY FRESH COTTON WOOL,1,2011-12-06 16:26:00,5.79,NaN,United Kingdom
142237,548561,22969,HOMEMADE JAM SCENTED CANDLES,12,2011-04-01 10:11:00,1.45,166090,United Kingdom
455021,575607,22312,OFFICE MUG WARMER POLKADOT,1,2011-11-10 12:37:00,5.79,140960,United Kingdom
239564,558063,21504,SKULLS GREETING CARD,24,2011-06-24 15:28:00,0.42,163950,United Kingdom
405802,571716,23307,SET OF 60 PANTRY DESIGN CAKE CASES,1,2011-10-18 17:05:00,1.25,NaN,United Kingdom
381121,569846,22907,PACK OF 20 NAPKINS PANTRY DESIGN,12,2011-10-06 13:42:00,0.85,134220,United Kingdom
429779,573576,22540,MINI JIGSAW CIRCUS PARADE,1,2011-10-31 14:09:00,0.83,140960,United Kingdom
96809,544586,22482,BLUE TEA TOWEL CLASSIC DESIGN,6,2011-02-21 15:04:00,1.25,173380,United Kingdom
291313,562444,22045,SPACEBOY GIFT WRAP,25,2011-08-04 18:44:00,0.42,147130,United Kingdom
408026,571929,37479P,CUBIC MUG FLOCK PINK ON BROWN,2,2011-10-19 16:47:00,0.39,NaN,United Kingdom
423738,573153,22616,PACK OF 12 LONDON TISSUES,120,2011-10-28 07:39:00,0.39,126780,France
382388,569900,20727,LUNCH BAG BLACK SKULL.,10,2011-10-06 16:17:00,1.65,176510,United Kingdom
80001,543013,71053,WHITE METAL LANTERN,7,2011-02-02 13:35:00,8.29,NaN,United Kingdom
298748,563036,22150,3 STRIPEY MICE FELTCRAFT,6,2011-08-11 14:55:00,1.95,148680,United Kingdom
86021,543533,20725,LUNCH BAG RED RETROSPOT,2,2011-02-09 13:00:00,4.96,NaN,United Kingdom
96565,544571,22615,PACK OF 12 CIRCUS PARADE TISSUES,24,2011-02-21 13:07:00,0.29,151460,United Kingdom
227808,556906,21154,RED RETROSPOT OVEN GLOVE,2,2011-06-15 13:07:00,1.25,128430,United Kingdom
308655,564044,85049C,ROMANTIC PINKS RIBBONS,1,2011-08-22 12:58:00,1.25,169520,United Kingdom
246689,558710,79063D,"RETRO PILL BOX , REVOLUTIONARY",4,2011-07-01 13:04:00,0.19,154830,United Kingdom
62824,541516,21111,"SWISS ROLL TOWEL, CHOCOLATE SPOTS",1,2011-01-18 17:34:00,2.46,NaN,United Kingdom
369417,569028,22732,3D VINTAGE CHRISTMAS STICKERS,18,2011-09-30 10:20:00,1.25,149110,EIRE
250192,559009,23344,JUMBO BAG 50'S CHRISTMAS,4,2011-07-05 12:47:00,2.08,155490,United Kingdom
383336,570016,22193,RED DINER WALL CLOCK,2,2011-10-07 10:06:00,8.5,149110,EIRE
184260,552681,21731,RED TOADSTOOL LED NIGHT LIGHT,1,2011-05-10 15:08:00,4.13,NaN,United Kingdom
498155,578511,23167,SMALL CERAMIC TOP STORAGE JAR,10,2011-11-24 13:27:00,0.83,179750,United Kingdom
125249,547034,48187,DOORMAT NEW ENGLAND,10,2011-03-20 10:30:00,6.75,182290,United Kingdom
359984,568206,84508C,BLUE CIRCLES DESIGN TEDDY,6,2011-09-25 15:32:00,2.55,148060,United Kingdom
486610,577742,22579,WOODEN TREE CHRISTMAS SCANDINAVIAN,1,2011-11-21 13:41:00,0.29,137550,United Kingdom
184043,552675,21558,SKULL LUNCH BOX WITH CUTLERY,1,2011-05-10 15:07:00,4.96,NaN,United Kingdom
512333,579512,22421,LIPSTICK PEN FUSCHIA,3,2011-11-29 16:47:00,0.83,NaN,United Kingdom
214841,555631,20971,PINK BLUE FELT CRAFT TRINKET BOX,1,2011-06-06 12:06:00,1.25,181180,United Kingdom
213535,555545,23203,JUMBO BAG DOILEY PATTERNS,10,2011-06-05 13:08:00,2.08,177350,United Kingdom
390967,570640,22898,CHILDRENS APRON APPLES DESIGN,8,2011-10-11 12:38:00,1.95,124740,Germany
428090,573413,21326,AGED GLASS SILVER T-LIGHT HOLDER,12,2011-10-30 16:12:00,0.65,154440,United Kingdom
222794,556459,22432,WATERING CAN PINK BUNNY,2,2011-06-10 17:25:00,4.13,NaN,United Kingdom
56260,541103,22702,BLACK AND WHITE CAT BOWL,6,2011-01-13 14:24:00,2.1,142150,United Kingdom
285575,561912,22047,EMPIRE GIFT WRAP,25,2011-08-01 11:08:00,0.42,131840,United Kingdom
125224,547030,22274,FELTCRAFT DOLL EMILY,6,2011-03-20 10:17:00,2.95,129480,United Kingdom
270481,560568,47566,PARTY BUNTING,8,2011-07-19 14:03:00,4.95,138950,United Kingdom
252258,559106,21715,GIRLS VINTAGE TIN SEASIDE BUCKET,1,2011-07-06 11:10:00,2.55,158890,United Kingdom
171109,551385,22854,CREAM SWEETHEART EGG HOLDER,6,2011-04-28 11:38:00,4.95,168140,United Kingdom
420249,572882,23503,PLAYING CARDS KEEP CALM & CARRY ON,12,2011-10-26 13:36:00,1.25,182260,United Kingdom
401729,571441,84673B,BLUE FLY SWAT,3,2011-10-17 13:31:00,1.63,140960,United Kingdom
540775,581492,22167,OVAL WALL MIRROR DIAMANTE,1,2011-12-09 10:03:00,8.29,NaN,United Kingdom
530242,580831,47593B,SCOTTIE DOGS BABY BIB,48,2011-12-06 11:39:00,0.39,144180,United Kingdom
191401,553356,21240,BLUE POLKADOT CUP,8,2011-05-16 14:05:00,0.85,140380,United Kingdom
447379,574950,23199,JUMBO BAG APPLES,1,2011-11-08 09:29:00,4.13,NaN,United Kingdom

In [15]:
# Convert 'UnitPrice' & Quantity column to float
df['UnitPrice'] = df['UnitPrice'].astype(float)
df['Quantity'] = df['Quantity'].astype(int)

In [16]:
#convert InvoiceDate to dt
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540884 non-null  object
 3   Quantity     541909 non-null  int32
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  object
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(1), int32(1), object(5)
memory usage: 31.0+ MB

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.dropna(inplace=True)

In [20]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [21]:
df.sample(50)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
156406,550137,22123,PING MICROWAVE APRON,12,2011-04-14 13:59:00,1.95,124770,Germany
25713,538382,22530,MAGIC DRAWING SLATE DOLLY GIRL,2,2010-12-12 11:37:00,0.42,172180,United Kingdom
414768,572484,22809,SET OF 6 T-LIGHTS SANTA,6,2011-10-24 13:50:00,2.95,172200,United Kingdom
213212,555524,23171,REGENCY TEA PLATE GREEN,12,2011-06-05 11:37:00,1.65,169230,United Kingdom
71745,542192,22415,WHITE TISSUE REAM,1,2011-01-26 11:27:00,7.95,140490,United Kingdom
244989,558565,21974,SET OF 36 PAISLEY FLOWER DOILIES,3,2011-06-30 13:58:00,1.45,148030,United Kingdom
362995,568531,21504,SKULLS GREETING CARD,12,2011-09-27 13:49:00,0.42,167130,United Kingdom
436999,574258,16054,POPART RECT PENCIL SHARPENER ASST,2,2011-11-03 13:50:00,0.12,168910,United Kingdom
302562,563438,22492,MINI PAINT SET VINTAGE,36,2011-08-16 12:59:00,0.65,137430,United Kingdom
187182,552951,23082,SET 6 PAPER TABLE LANTERN HEARTS,12,2011-05-12 12:05:00,3.75,149880,United Kingdom
310127,564166,23314,VINTAGE CHRISTMAS TABLECLOTH,2,2011-08-23 13:40:00,12.50,150890,United Kingdom
110186,545681,47567B,TEA TIME KITCHEN APRON,3,2011-03-06 11:28:00,5.95,169230,United Kingdom
382051,569897,21086,SET/6 RED SPOTTY PAPER CUPS,2,2011-10-06 16:01:00,0.65,178130,United Kingdom
22335,538163,22755,SMALL PURPLE BABUSHKA NOTEBOOK,7,2010-12-09 17:27:00,0.85,178410,United Kingdom
291647,562467,84949,SILVER HANGING T-LIGHT HOLDER,6,2011-08-05 11:50:00,1.65,135130,United Kingdom
20385,538040,22659,LUNCH BOX I LOVE LONDON,3,2010-12-09 13:08:00,1.95,165200,United Kingdom
33909,539307,21873,IF YOU CAN'T STAND THE HEAT MUG,72,2010-12-16 17:43:00,0.42,136940,United Kingdom
309658,564135,23298,SPOTTY BUNTING,3,2011-08-23 11:12:00,4.95,165500,United Kingdom
298264,563012,22439,6 ROCKET BALLOONS,3,2011-08-11 12:00:00,0.65,172840,United Kingdom
315474,564728,23084,RABBIT NIGHT LIGHT,48,2011-08-28 12:43:00,1.79,131990,United Kingdom
310250,564172,21174,POTTERING IN THE SHED METAL SIGN,2,2011-08-23 14:19:00,2.08,160330,United Kingdom
438871,574338,23378,PACK OF 12 50'S CHRISTMAS TISSUES,24,2011-11-04 10:05:00,0.39,141500,United Kingdom
246388,558700,21222,SET/4 BADGES BEETLES,1,2011-07-01 12:33:00,1.25,179200,United Kingdom
438977,574345,23109,PACK OF SIX LED TEA LIGHTS,6,2011-11-04 10:18:00,2.89,158450,United Kingdom
521197,580319,23358,HOT STUFF HOT WATER BOTTLE,18,2011-12-02 15:39:00,1.25,150780,United Kingdom
43562,C540097,22113,GREY HEART HOT WATER BOTTLE,4,2011-01-04 15:46:00,3.75,153730,United Kingdom
61585,541430,21114,LAVENDER SCENTED FABRIC HEART,40,2011-01-18 09:50:00,1.25,123560,Portugal
274330,560896,22469,HEART OF WICKER SMALL,12,2011-07-21 17:26:00,1.65,156230,United Kingdom
18065,537794,21506,"FANCY FONT BIRTHDAY CARD,",12,2010-12-08 13:01:00,0.42,167130,United Kingdom
403028,571544,22810,SET OF 6 T-LIGHTS SNOWMEN,2,2011-10-17 16:53:00,2.95,177570,United Kingdom
509889,579408,23356,LOVE HOT WATER BOTTLE,2,2011-11-29 12:34:00,5.95,147010,United Kingdom
126660,547093,22374,AIRLINE BAG VINTAGE JET SET RED,4,2011-03-21 08:20:00,4.25,147620,United Kingdom
75391,542590,22626,BLACK KITCHEN SCALES,1,2011-01-28 16:18:00,8.50,179200,United Kingdom
165297,550779,21124,SET/10 BLUE POLKADOT PARTY CANDLES,24,2011-04-20 13:36:00,1.25,175110,United Kingdom
360852,568314,22670,FRENCH WC SIGN BLUE METAL,6,2011-09-26 12:58:00,1.25,143870,United Kingdom
518873,580126,23076,ICE CREAM SUNDAE LIP GLOSS,24,2011-12-01 17:20:00,1.25,125620,France
524554,580600,23266,SET OF 3 WOODEN STOCKING DECORATION,4,2011-12-05 11:13:00,1.25,128410,United Kingdom
334815,566270,84030E,ENGLISH ROSE HOT WATER BOTTLE,4,2011-09-11 13:40:00,4.25,165230,United Kingdom
434695,574056,22554,PLASTERS IN TIN WOODLAND ANIMALS,96,2011-11-02 14:09:00,1.45,146460,Netherlands
343758,566967,22941,CHRISTMAS LIGHTS 10 REINDEER,2,2011-09-15 18:05:00,8.50,167460,United Kingdom
171391,551414,84946,ANTIQUE SILVER T-LIGHT GLASS,12,2011-04-28 13:35:00,1.25,156220,United Kingdom
78862,542898,85061W,WHITE JEWELLED HEART DECORATION,5,2011-02-01 14:01:00,0.85,161100,United Kingdom
271177,560650,16162M,THE KING GIFT BAG 25x24x12cm,6,2011-07-20 11:38:00,0.42,155290,United Kingdom
276024,561027,47559B,TEA TIME OVEN GLOVE,50,2011-07-24 10:54:00,1.06,138020,United Kingdom
284450,561873,20969,RED FLORAL FELTCRAFT SHOULDER BAG,36,2011-07-31 11:48:00,3.39,133160,United Kingdom
398237,571229,23482,PEARLISED IVORY HEART LARGE,2,2011-10-14 14:04:00,1.65,154530,United Kingdom
439205,574368,23035,DRAWER KNOB CERAMIC IVORY,6,2011-11-04 10:59:00,1.45,130040,United Kingdom
433777,573993,23511,EMBROIDERED RIBBON REEL EMILY,6,2011-11-02 11:23:00,2.08,167900,United Kingdom
295407,562787,M,Manual,1,2011-08-09 13:44:00,208.34,155810,United Kingdom
311442,564300,22989,SET 2 PANTRY DESIGN TEA TOWELS,4,2011-08-24 11:31:00,3.25,167230,United Kingdom

##### Task 2

In [ ]:
# Save descriptions to a text file for training
df['Description'].to_csv('descriptions.txt', index=False, header=False)

In [10]:
import fasttext

In [ ]:
# Train FastText model
model = fasttext.train_unsupervised('descriptions.txt', model='skipgram', dim=100)
# Define the path where you want to save the model in Google Drive
save_path = './fasttext_model.bin'

# Save the FastText model to the specified path in Google Drive
model.save_model(save_path)

In [ ]:
def get_fasttext_embedding(text, model):
    words = text.split()
    word_vectors = [model.get_word_vector(word) for word in words]
    if word_vectors:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(model.get_dimension())

# Generate FastText embeddings for product descriptions
df['Embedding'] = df['Description'].apply(lambda x: get_fasttext_embedding(x, model))

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Embedding
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,178500,United Kingdom,"[-0.11460948, 0.09612513, -0.14942448, 0.08873..."
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,178500,United Kingdom,"[0.44666132, 0.11083678, -0.1314929, 0.2498146..."
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,178500,United Kingdom,"[-0.4788653, 0.21503608, -0.240311, -0.0131647..."
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,178500,United Kingdom,"[-0.70990545, -0.20370954, -0.114887714, -0.63..."
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,178500,United Kingdom,"[0.16695455, -0.0054392293, -0.49739924, -0.50..."

In [ ]:
!pip install pinecone-client[grpc]

Collecting pinecone-client[grpc]
  Downloading pinecone_client-4.1.1-py3-none-any.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.2/216.2 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: certifi>=2019.11.17 in /usr/local/lib/python3.10/dist-packages (from pinecone-client[grpc]) (2024.6.2)
Collecting pinecone-plugin-interface<0.0.8,>=0.0.7 (from pinecone-client[grpc])
  Downloading pinecone_plugin_interface-0.0.7-py3-none-any.whl (6.2 kB)
Requirement already satisfied: tqdm>=4.64.1 in /usr/local/lib/python3.10/dist-packages (from pinecone-client[grpc]) (4.66.4)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.10/dist-packages (from pinecone-client[grpc]) (4.12.2)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from pinecone-client[grpc]) (2.0.7)
Requirement already satisfied: googleapis-common-protos>=1.53.0 in /usr/local/lib/python3.10/dist-packages (from pinecone-client[grpc]) (1.63.1)
Requirement already satisfied: grpcio>=1.44.0 in /usr/local/lib/python3.10/dist-packages (from pinecone-client[grpc]) (1.64.1)
Collecting lz4>=3.1.3 (from pinecone-client[grpc])
  Downloading lz4-4.3.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 11.6 MB/s eta 0:00:00
Collecting protobuf<5.0,>=4.25 (from pinecone-client[grpc])
  Downloading protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 11.9 MB/s eta 0:00:00
Collecting protoc-gen-openapiv2<0.0.2,>=0.0.1 (from pinecone-client[grpc])
  Downloading protoc_gen_openapiv2-0.0.1-py3-none-any.whl (7.9 kB)
Installing collected packages: protobuf, pinecone-plugin-interface, lz4, pinecone-client, protoc-gen-openapiv2
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.15.0 requires protobuf<4.21,>=3.20.3; python_version < "3.11", but you have protobuf 4.25.3 which is incompatible.
Successfully installed lz4-4.3.3 pinecone-client-4.1.1 pinecone-plugin-interface-0.0.7 protobuf-4.25.3 protoc-gen-openapiv2-0.0.1

In [60]:
from pinecone import Pinecone, ServerlessSpec

pc = Pinecone(api_key="API-key")
index_name = 'products'
index = pc.Index(index_name)

In [ ]:
# Function to chunk the data into smaller batches
def chunk_data(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

# Prepare data for upsert
vectors = []
for product_id, embedding, description in zip(df['StockCode'], df['Embedding'], df['Description']):
    if embedding is not None and np.count_nonzero(embedding) > 0:  # Ensure the embedding is not None and has non-zero values
        vectors.append((str(product_id), embedding.tolist(), {'description': description}))

# Set batch size
batch_size = 100

# Upsert data in batches
for batch in chunk_data(vectors, batch_size):
    index.upsert(vectors=batch)

Given the characteristics of product vectors, such as potentially high dimensionality and sparsity, cosine similarity is a suitable choice. It efficiently captures the similarity between vectors while mitigating the effects of varying vector magnitudes.

In [13]:
# Load FastText model
fasttext_model = fasttext.load_model('./fasttext_model.bin')
def embed_query(query, model):
    tokenized_query = query.split()
    # Average the vectors for each word in the query
    query_vector = sum(fasttext_model.get_word_vector(word) for word in tokenized_query) / len(tokenized_query)
    return query_vector

# User's natural language query
user_query = "WHITE METAL LANTERN"
query_vector = embed_query(user_query, fasttext_model)

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

In [14]:
query_vector

array([ 0.44666132,  0.11083678, -0.1314929 ,  0.24981463,  0.19736965,
        0.17026208, -0.03710908,  0.02662694,  0.55260426,  0.4548335 ,
       -0.07288501,  0.51020914,  0.21083719, -0.04575443, -0.6151672 ,
        0.3070401 ,  0.13233636,  0.00234846,  0.06401508, -0.842669  ,
       -0.16725223,  0.44720182,  0.62782437, -0.68128824,  0.15916334,
       -0.1251542 ,  0.09077978, -0.6294453 , -0.32758987,  0.9917515 ,
       -0.25425005, -0.23003705, -0.2475332 , -0.7591589 , -0.39162531,
        0.1289454 ,  0.18795653, -0.6376439 ,  0.03992735, -0.41210428,
        0.5279362 , -0.09519234,  0.9488327 ,  0.24464051, -0.33880842,
       -0.4070501 , -0.3034578 ,  0.07593399,  0.1864974 ,  0.46712494,
       -0.29583347,  0.26279625, -0.3914875 , -0.0435233 , -0.6962425 ,
       -0.7149903 , -0.550914  ,  0.51578456,  0.21285896,  0.11687418,
       -0.6606922 , -0.08061361,  0.85326606,  0.61663467, -0.66356367,
       -0.05331155,  0.10211375,  0.32941535,  0.21580231, -0.07718083,
       -0.4111255 , -0.27263072, -0.09142091, -0.01340326,  0.16741174,
        0.01318468,  0.27267516,  0.3799648 ,  0.06576844, -0.18988025,
       -0.32178447,  0.2398838 ,  0.30895856,  0.00649941, -0.1705802 ,
        0.11211104,  0.0840352 , -0.14051296, -0.43514884, -0.3156034 ,
        0.52104896,  0.48307204,  0.5152708 , -0.8845194 ,  0.27427888,
       -0.639414  ,  0.86248046,  0.48725462, -0.0760197 ,  0.32121518],
      dtype=float32)

In [15]:
# Query Pinecone with the query vector
response = index.query(
    vector=query_vector.tolist(),  # Convert the query vector to a list
    top_k=5,  # Number of top results to return
    include_values=True,  # Include the values in the response
    include_metadata=True  # Include metadata in the response
)

# Display the top 3 similar products
top_products = response['matches']
for i, product in enumerate(top_products, start=1):
    print(f"Rank {i}:")
    if 'metadata' in product and 'description' in product['metadata']:
        print(f"Description: {product['metadata']['description']}")
    else:
        print("Description: N/A")

    print(f"Score: {product.get('score', 'Score not available')}\n")

Rank 1:
Description: WHITE MOROCCAN METAL LANTERN
Score: 0.976348042

Rank 2:
Description: WHITE LOVEBIRD LANTERN
Score: 0.871218503

Rank 3:
Description: HANGING METAL STAR LANTERN
Score: 0.812855184

Rank 4:
Description: HANGING METAL HEART LANTERN
Score: 0.801143

Rank 5:
Description: FRENCH CARRIAGE LANTERN
Score: 0.78852421

### Module 2

In [ ]:
!apt-get install tesseract-ocr
!pip install pytesseract

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (5.3.4+git6391-34693cd7-1ppa1~jammy1).
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.
Requirement already satisfied: pytesseract in /usr/local/lib/python3.10/dist-packages (0.3.10)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from pytesseract) (24.1)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from pytesseract) (9.4.0)

In [16]:
from PIL import Image
import pytesseract

In [20]:
# Open an image file
image1 = Image.open('./dan.png')
#image2 = Image.open('./scc.png')

# Perform OCR using Tesseract
text1 = pytesseract.image_to_string(image1)
#text2 = pytesseract.image_to_string(image2)

# Print the extracted text
print(text1)
#print(text2)

6 unread messages

Aw far ogah sheddy oD

Na about that laptop aren

Omo things hard for me
See my house rent landlord call me

You go help a brother too
Make | send u 40k for the. System

Abeg na help u go help me neg

If you gree make | send the money

14:22

14:23

14:51

In [22]:
cnn_df = pd.read_csv('CNN_Model_Train_Data.csv')
cnn_df['StockCode'] = cnn_df['StockCode'].apply(remove_non_standard_characters)

In [23]:
cnn_df

  StockCode
0     22384
1     22727
2     22112
3     23298
4     20726
5     21034
6     21931
7     22139
8     22077
9     22423

In [24]:
from sklearn.preprocessing import LabelEncoder

stock_ids = np.array(['22384', '22727', '22112', '23298', '20726', '21034', '21931', '22139', '22077', '22423'])

# Create and fit the label encoder
label_encoder = LabelEncoder()
label_encoder.fit(stock_ids)

# Transform Stock IDs to numeric labels
numeric_labels = label_encoder.transform(stock_ids)
print("Numeric Labels:", numeric_labels)

# To reverse the transformation
original_labels = label_encoder.inverse_transform(numeric_labels)
print("Original Labels:", original_labels)

Numeric Labels: [6 8 4 9 0 1 2 5 3 7]
Original Labels: ['22384' '22727' '22112' '23298' '20726' '21034' '21931' '22139' '22077'
 '22423']

In [25]:
import pickle

# Save the label encoder
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label_encoder, file)

In [ ]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.21.0-py3-none-any.whl (9.5 MB)
     ---------------------------------------- 9.5/9.5 MB 551.3 kB/s eta 0:00:00
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\shedrack\anaconda3\lib\site-packages (from selenium) (4.12.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\shedrack\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Collecting trio~=0.17
  Downloading trio-0.25.1-py3-none-any.whl (467 kB)
     ------------------------------------ 467.7/467.7 kB 975.3 kB/s eta 0:00:00
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\shedrack\anaconda3\lib\site-packages (from selenium) (1.26.11)
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Collecting sniffio>=1.3.0
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting exceptiongroup
  Downloading exceptiongroup-1.2.1-py3-none-any.whl (16 kB)
Requirement already satisfied: idna in c:\users\shedrack\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Collecting attrs>=23.2.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ---------------------------------------- 60.8/60.8 kB 3.2 MB/s eta 0:00:00
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: sortedcontainers in c:\users\shedrack\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\shedrack\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\shedrack\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\shedrack\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Collecting h11<1,>=0.9.0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     -------------------------------------- 58.3/58.3 kB 384.2 kB/s eta 0:00:00
Installing collected packages: sniffio, h11, exceptiongroup, attrs, wsproto, outcome, trio, trio-websocket, selenium
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.2.0
    Uninstalling sniffio-1.2.0:
      Successfully uninstalled sniffio-1.2.0
  Attempting uninstall: attrs
    Found existing installation: attrs 21.4.0
    Uninstalling attrs-21.4.0:
      Successfully uninstalled attrs-21.4.0
Successfully installed attrs-23.2.0 exceptiongroup-1.2.1 h11-0.14.0 outcome-1.3.0.post0 selenium-4.21.0 sniffio-1.3.1 trio-0.25.1 trio-websocket-0.11.1 wsproto-1.2.0

In [ ]:
import requests
from bs4 import BeautifulSoup
import os
import time
from urllib.parse import urljoin
from urllib.request import urlretrieve

def get_all_product_page_urls(start_page_url, max_pages=10, delay=7):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
    product_links = []
    current_page_url = start_page_url

    for page_num in range(max_pages):
        response = requests.get(current_page_url, headers=headers)
        if response.status_code != 200:
            print(f"Failed to retrieve the page. Status code: {response.status_code}")
            break

        soup = BeautifulSoup(response.content, 'lxml')
        for a in soup.find_all('a', class_='item-img'):
            href = a.get('href')
            if href:
                product_links.append(urljoin(start_page_url, href))

        # Find the link to the next page
        next_page_tag = soup.find('a', class_='list-tool-pagination-next')
        if not next_page_tag or 'href' not in next_page_tag.attrs:
            break
        current_page_url = urljoin(start_page_url, next_page_tag['href'])
        print(f"Moving to next page: {current_page_url}")

        # Wait for a few seconds before moving to the next page
        time.sleep(delay)

    return product_links

def get_product_image_and_title(product_url):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
    response = requests.get(product_url, headers=headers)

    if response.status_code != 200:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        return None, None

    soup = BeautifulSoup(response.content, 'lxml')

    img_tag = soup.find('img', class_='product-view-img-original')
    image_url = img_tag.get('src') if img_tag else None

    title_tag = soup.find('h1', class_='product-title')
    title = title_tag.text.strip() if title_tag else None

    return image_url, title

def download_images(image_urls, titles, save_dir):
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    for i, (url, title) in enumerate(zip(image_urls, titles)):
        try:
            title_safe = title.replace(' ', '_').replace('/', '_')[:50]  # Make the title filesystem safe
            image_path = os.path.join(save_dir, f'{title_safe}_{i+1}.jpg')
            urlretrieve(url, image_path)
            print(f'Downloaded {url} to {image_path}')
        except Exception as e:
            print(f'Failed to download {url}: {e}')

In [ ]:
# Define the start page URL of the e-commerce listings
start_page_url = 'https://www.newegg.com/p/pl?d=screwdriver'
base_url = 'https://www.newegg.com'

# Scrape product page URLs from multiple pages
product_page_urls = get_all_product_page_urls(start_page_url, max_pages=10, delay=7)

# Scrape image URLs and titles from each product page
image_urls = []
titles = []
for product_url in product_page_urls:
    image_url, title = get_product_image_and_title(product_url)
    if image_url and title:
        image_urls.append(image_url)
        titles.append(title)

# Directory to save downloaded images
save_dir = 'downloaded_images'

# Download images
download_images(image_urls, titles, save_dir)

Downloaded https://c1.neweggimages.com/ProductImage/BDW5S2303060JEEKCE4.jpg to downloaded_images\KUTUMAI_Screwdriver_Bits_Magnetic_Portable_Case_63_1.jpg
Downloaded https://c1.neweggimages.com/ProductImage/B6MWS220105053CEK39.jpg to downloaded_images\WIREHARD_62_in_1_Precision_Screwdriver_Set_Repair__2.jpg
Downloaded https://c1.neweggimages.com/ProductImage/B6MWS220105053CEK39.jpg to downloaded_images\WIREHARD_62_in_1_Precision_Screwdriver_Set_Repair__3.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES2307180CQRER44.jpg to downloaded_images\Screwdriver_Sets_142-Piece_Electronics_Precision_S_4.jpg
Downloaded https://c1.neweggimages.com/ProductImage/BKWBS2310270K681U62.jpg to downloaded_images\Deli_65-in-1_Precision_Screwdriver_Set_Small_Preci_5.jpg
Downloaded https://c1.neweggimages.com/ProductImage/B6MWS22013118Z87528.jpg to downloaded_images\WIREHARD_50_in_1_Precision_Screwdriver_Set_Repair__6.jpg
Downloaded https://c1.neweggimages.com/ProductImage/AGS6S210326YCnXI.jpg to downloaded_images\Aigrous_Screwdriver_Set_for_Computer,_PC,Phone,iPh_7.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES2307180CQRER44.jpg to downloaded_images\Screwdriver_Sets_142-Piece_Electronics_Precision_S_8.jpg
Downloaded https://c1.neweggimages.com/ProductImage/ARZSS24013004M3Q5D0.jpg to downloaded_images\SEQURE_ES666_Smart_Somatosensory_Recognition_Elect_9.jpg
Downloaded https://c1.neweggimages.com/ProductImage/BKWBS2310250CYMQ899.jpg to downloaded_images\Deli_Hand_Screwdriver_Set_8_in_1_Phillips_Slotted__10.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES24041803G03S44.jpg to downloaded_images\Screwdriver_Sets_142-Piece_Electronics_Precision_S_11.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES2307180EQ6Z12C.jpg to downloaded_images\140_in_1_Precision_Screwdriver_Set,_Professional_C_12.jpg
Downloaded https://c1.neweggimages.com/ProductImage/AGS6S240515064IGH17.jpg to downloaded_images\Aigrous_Electronics_Precision_Screwdriver_Sets_164_13.jpg
Downloaded https://c1.neweggimages.com/ProductImage/ARZSS210916D528B.jpg to downloaded_images\SEQURE_ES-180_Micro_Electronic_Screwdriver_Bit_Set_14.jpg
Downloaded https://c1.neweggimages.com/ProductImage/96-832-026-02.jpg to downloaded_images\Stanley_4-in-1_Bi-Material_Pocket_Driver_15.jpg
Downloaded https://c1.neweggimages.com/ProductImage/BKWBS2310270LWK1B1F.jpg to downloaded_images\Deli_21_in_1_Mini_Screwdriver_Set_Small_Precision__16.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES23091206L4LR06.jpg to downloaded_images\Rj45_Crimp_Tool_Kit_Pass_Through_and_Standard_Cat6_17.jpg
Downloaded https://c1.neweggimages.com/ProductImage/AGS6S2402150OTYQG2F.jpg to downloaded_images\Aigrous_Precision_Screwdriver_Set,_Professional_Gr_18.jpg
Downloaded https://c1.neweggimages.com/ProductImage/AVBJS211011F80BE.jpg to downloaded_images\Mini_Electric_Screwdriver,_3_LED_Lights,_Rechargea_19.jpg
Downloaded https://c1.neweggimages.com/ProductImage/BEDSS2304050C6IQ4BA.jpg to downloaded_images\UHAND_TOOL_Universal_Network_Wire_Stripping_Tool_f_20.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES23041304L0MZE2.jpg to downloaded_images\Repair_Replacement_Screws_with_Screwdriver_for_Mac_21.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES230413041INBC2.jpg to downloaded_images\2_Sets_Replacement_Screws_with_Screwdriver_for_Mac_22.jpg
Downloaded https://c1.neweggimages.com/ProductImage/ARZSS24013004M3Q5D0.jpg to downloaded_images\SEQURE_ES666_Smart_Somatosensory_Recognition_Elect_23.jpg
Downloaded https://c1.neweggimages.com/ProductImage/V0KK_1_201909171430920829.jpg to downloaded_images\Torx_Screwdriver_Bits_1_4-Inch_Hex_Shank_150mm_Len_24.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES2302200IMW9FF3.jpg to downloaded_images\M.2_Screw_Kit,NVMe_Screw_m.2_SSD_Mounting_Kit,Comp_25.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES23042303F6622F.jpg to downloaded_images\PCIe_NVMe_M.2_SSD_Mounting_Screws_Kit_for_Asus_Gig_26.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RES230421062PAVBD.jpg to downloaded_images\PCIe_NVMe_M.2_SSD_Mounting_Screws_Kit_for_Asus_Gig_27.jpg
Downloaded https://c1.neweggimages.com/ProductImage/BKWBS2309080CO40H8A.jpg to downloaded_images\Deli_45_in_1_Precision_Screwdriver_Set_Small_Screw_28.jpg
Downloaded https://c1.neweggimages.com/ProductImage/BKWBS23090808216X69.jpg to downloaded_images\6PCS_Mini_Screwdriver_Set_with_Case,Precision_Scre_29.jpg
Failed to download https://c1.neweggimages.com/ProductImage/A27CD2308110PYYAS47.jpg: HTTP Error 503: Service Unavailable
Failed to download https://c1.neweggimages.com/ProductImage/A27CD2308110Q0BGN4E.jpg: [Errno 22] Invalid argument: 'downloaded_images\\35_in_1_Screwdriver_Bit_Set_1_4"_Hex_Shank_Torx_Sl_31.jpg'
Failed to download https://c1.neweggimages.com/ProductImage/A27CD2308110Q00SED5.jpg: [Errno 22] Invalid argument: 'downloaded_images\\12_in_1_Screwdriver_Bit_Set_1_4"_Hex_Shank_Torx_Sl_32.jpg'
Failed to download https://c1.neweggimages.com/ProductImage/A27CD2308110Q00G1A7.jpg: [Errno 22] Invalid argument: 'downloaded_images\\13_in_1_Screwdriver_Bit_Set_1_4"_Hex_Shank_Torx_Sl_33.jpg'
Downloaded https://c1.neweggimages.com/ProductImage/A14R_1_20140428507910179.jpg to downloaded_images\Stanley_Tools_6-Piece_Precision_Screwdriver_Set_34.jpg
Downloaded https://c1.neweggimages.com/ProductImage/A4RE_131414594063801764lHmHOrbaYK.jpg to downloaded_images\CORN_58_in_1_with_54_Bit_Magnetic_Driver_Kit,_Prec_35.jpg
Downloaded https://c1.neweggimages.com/ProductImage/V0KK_1_201912041140170107.jpg to downloaded_images\Phillips_Bits_5pcs_1_4-Inch_Hex_Shank_Magnetic_Cro_36.jpg
Downloaded https://c1.neweggimages.com/ProductImage/AJTV_1_20191010515430367.jpg to downloaded_images\Screwdriver_Bit_Set_12-in-1_Magnetic_Screw_Driver__37.jpg
Failed to download https://c1.neweggimages.com/ProductImage/A27CD2308110PZJAE91.jpg: [Errno 22] Invalid argument: 'downloaded_images\\20_in_1_Screwdriver_Bit_Set_1_4"_Hex_Shank_Torx_Sl_38.jpg'
Failed to download https://c1.neweggimages.com/ProductImage/A27CD2308110PZJLY4C.jpg: [Errno 22] Invalid argument: 'downloaded_images\\10_in_1_Screwdriver_Bit_Set_1_4"_Hex_Shank_Torx_Sq_39.jpg'
Failed to download https://c1.neweggimages.com/ProductImage/A27CD2308110PZ8QSAF.jpg: [Errno 22] Invalid argument: 'downloaded_images\\11_in_1_Screwdriver_Bit_Set_1_4"_Hex_Shank_Torx_Sl_40.jpg'
Failed to download https://c1.neweggimages.com/ProductImage/A27CD2308110PZU2K1B.jpg: [Errno 22] Invalid argument: 'downloaded_images\\21_in_1_Screwdriver_Bit_Set_1_4"_Hex_Shank_Torx_Sl_41.jpg'
Failed to download https://c1.neweggimages.com/ProductImage/A27C_1_20190917462898426.jpg: [Errno 22] Invalid argument: 'downloaded_images\\Magnetic_Screwdriver_Set_5_in_1,__1_4"_Hex_Shank_7_42.jpg'
Failed to download https://c1.neweggimages.com/ProductImage/V06N_1_201812181125910026.jpg: [Errno 22] Invalid argument: 'downloaded_images\\5pcs_50mm_Long_1_4"_Hex_Shank_T6_Torx_Head_Screwdr_43.jpg'

First check the url for a product, open the product then download the image along with it's title and go to the next page with a delay of 7 seconds

Each item was downloaded and saved in a directory for the CNN model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [47]:
import os
stock_codes = cnn_df['StockCode'].astype(str).tolist()

def load_and_preprocess_images(stock_codes, base_dir, image_size=(128, 128)):
    images = []
    labels = []

    for stock_code in stock_codes:
        product_dir = os.path.join(base_dir, stock_code)
        if os.path.exists(product_dir):
            for image_file in os.listdir(product_dir):
                image_path = os.path.join(product_dir, image_file)
                image = Image.open(image_path).convert('RGB')
                image = image.resize(image_size)
                image = np.array(image) / 255.0  # Normalize to [0, 1]
                images.append(image)
                labels.append(stock_code)
        else:
            print(f"Directory not found for stock code: {stock_code}")

    return np.array(images), np.array(labels)

In [49]:
# Define the base directory for images and load them
base_dir = './products'
images, labels = load_and_preprocess_images(stock_codes, base_dir)

print(f"Loaded {len(images)} images")

Loaded 391 images

In [50]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(labels)

# Convert labels to categorical (one-hot encoding)
from tensorflow.keras.utils import to_categorical
labels_categorical = to_categorical(labels_encoded)

print(f"Labels shape: {labels_categorical.shape}")

Labels shape: (391, 10)

In [51]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

def create_cnn_model(input_shape, num_classes):
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Define input shape and number of classes
input_shape = (128, 128, 3)
num_classes = len(label_encoder.classes_)

# Create the model
model = create_cnn_model(input_shape, num_classes)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 126, 126, 32)      896

 max_pooling2d (MaxPooling2D  (None, 63, 63, 32)       0
 )

 conv2d_1 (Conv2D)           (None, 61, 61, 64)        18496

 max_pooling2d_1 (MaxPooling  (None, 30, 30, 64)       0
 2D)

 conv2d_2 (Conv2D)           (None, 28, 28, 128)       73856

 max_pooling2d_2 (MaxPooling  (None, 14, 14, 128)      0
 2D)

 flatten (Flatten)           (None, 25088)             0

 dense (Dense)               (None, 128)               3211392

 dropout (Dropout)           (None, 128)               0

 dense_1 (Dense)             (None, 10)                1290

=================================================================
Total params: 3,305,930
Trainable params: 3,305,930
Non-trainable params: 0
_________________________________________________________________

In [52]:
from sklearn.model_selection import train_test_split

# Split the data
X_train, X_val, y_train, y_val = train_test_split(images, labels_categorical, test_size=0.2, random_state=42)

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val))

Epoch 1/10
10/10 [==============================] - 5s 409ms/step - loss: 2.3221 - accuracy: 0.1923 - val_loss: 2.1969 - val_accuracy: 0.1646
Epoch 2/10
10/10 [==============================] - 3s 318ms/step - loss: 1.9181 - accuracy: 0.3462 - val_loss: 1.8108 - val_accuracy: 0.3165
Epoch 3/10
10/10 [==============================] - 4s 393ms/step - loss: 1.4937 - accuracy: 0.5032 - val_loss: 1.4707 - val_accuracy: 0.5190
Epoch 4/10
10/10 [==============================] - 3s 306ms/step - loss: 1.0830 - accuracy: 0.6731 - val_loss: 1.1265 - val_accuracy: 0.6329
Epoch 5/10
10/10 [==============================] - 3s 316ms/step - loss: 0.8299 - accuracy: 0.7372 - val_loss: 0.9967 - val_accuracy: 0.6582
Epoch 6/10
10/10 [==============================] - 4s 369ms/step - loss: 0.6159 - accuracy: 0.8045 - val_loss: 0.8799 - val_accuracy: 0.7089
Epoch 7/10
10/10 [==============================] - 3s 320ms/step - loss: 0.4825 - accuracy: 0.8590 - val_loss: 0.7767 - val_accuracy: 0.7722
Epoch 8/10
10/10 [==============================] - 3s 325ms/step - loss: 0.3230 - accuracy: 0.9071 - val_loss: 0.8780 - val_accuracy: 0.7342
Epoch 9/10
10/10 [==============================] - 3s 333ms/step - loss: 0.3055 - accuracy: 0.8814 - val_loss: 0.8738 - val_accuracy: 0.7595
Epoch 10/10
10/10 [==============================] - 3s 324ms/step - loss: 0.2263 - accuracy: 0.9295 - val_loss: 0.8755 - val_accuracy: 0.7468

In [53]:
# Evaluate the model
val_loss, val_accuracy = model.evaluate(X_val, y_val)
print(f"Validation accuracy: {val_accuracy * 100:.2f}%")

3/3 [==============================] - 0s 81ms/step - loss: 0.8755 - accuracy: 0.7468
Validation accuracy: 74.68%

In [64]:
# Save the trained model to the specified path in Google Drive
model.save('cnn_model.h5')

# Save the label encoder
import pickle

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)

In [55]:
def extract_text_from_image(image_path):
    img = Image.open(image_path)
    text = pytesseract.image_to_string(img)
    return text

def get_fasttext_embedding(text, model):
    words = text.split()
    word_vectors = [model.get_word_vector(word) for word in words]
    if word_vectors:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(model.get_dimension())

def query_pinecone(embedding, top_k=5):
    response = index.query(
        vector=embedding.tolist(),
        top_k=top_k,
        include_values=True,
        include_metadata=True
    )
    return response['matches']

In [56]:
# Example: Extract text from uploaded image and query Pinecone
uploaded_image_path = './testimg.png'
extracted_text = pytesseract.image_to_string(uploaded_image_path)

embedding = get_fasttext_embedding(extracted_text, fasttext_model)
top_products = query_pinecone(embedding, top_k=5)

for i, product in enumerate(top_products, start=1):
    print(f"Rank {i}:")
    print(f"Description: {product['metadata']['description']}")
    print(f"Score: {product['score']}\n")
print(f"Extracted Text: {extracted_text}")

Rank 1:
Description: PINK HANGING HEART T-LIGHT HOLDER
Score: 0.940985143

Rank 2:
Description: HANGING HEART ZINC T-LIGHT HOLDER
Score: 0.936896324

Rank 3:
Description: RED HANGING HEART T-LIGHT HOLDER
Score: 0.935551465

Rank 4:
Description: CREAM HANGING HEART T-LIGHT HOLDER
Score: 0.928866625

Rank 5:
Description: HANGING HEART JAR T-LIGHT HOLDER
Score: 0.918202341

Extracted Text: WHITE HANGING HEART T-LIGHT HOLDER|

In [66]:
# Load the model
from tensorflow.keras.models import load_model

cnn_model = load_model('cnn_model.h5')

# Load the label encoder
with open('label_encoder.pkl', 'rb') as file:
    label_encoder = pickle.load(file)

In [73]:
def preprocess_image(image_path, image_size=(128, 128)):
    image = Image.open(image_path).convert('RGB')
    image = image.resize(image_size)
    image = np.array(image) / 255.0  # Normalize to [0, 1]
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    return image

def predict_image(model, image_path, label_encoder):
    # Preprocess the image
    image = preprocess_image(image_path)

    # Make prediction
    predictions = model.predict(image)
    predicted_class = np.argmax(predictions, axis=1)

    # Decode the label
    predicted_label = label_encoder.inverse_transform(predicted_class)

    return predicted_label[0]


def query_pinecone_by_id(stock_id, index, top_k=5):
    # Query Pinecone using the Stock ID
    response = index.query(
        namespace='',  # Specify namespace if used
        id=str(stock_id),  # Use the stock_id as the query id
        top_k=top_k,
        include_values=True,
        include_metadata=True
    )

    return response

def display_results(response):
    # Display the top similar products
    top_products = response['matches']
    for i, product in enumerate(top_products, start=1):
        print(f"Rank {i}:")
        print(f"Description: {product['metadata']['description']}")
        print(f"Score: {product['score']}\n")

def process_and_query(image_path, cnn_model, label_encoder, pinecone_index):
    # Predict the image class
    predicted_stock_id = predict_image(cnn_model, image_path, label_encoder)
    print(f"Predicted Stock ID: {predicted_stock_id}")

    # Query Pinecone using the predicted Stock ID
    response = query_pinecone_by_id(predicted_stock_id, pinecone_index)

    # Display the results
    display_results(response)

In [74]:
# Path to the image you want to process
image_path = './DJI_Avata_Pro-View_Combo_(DJI_Goggles_2)_-_With_Mo_18.jpg'

# Run the full process
process_and_query(image_path, cnn_model, label_encoder, index)

1/1 [==============================] - 0s 20ms/step
Predicted Stock ID: 20726
Rank 1:
Description: LUNCH BAG WOODLAND
Score: 0.99977386

Rank 2:
Description: WOODLAND CHARLOTTE BAG
Score: 0.94308424

Rank 3:
Description: JUMBO BAG WOODLAND ANIMALS
Score: 0.909772873

Rank 4:
Description: LUNCH BAG SUKI DESIGN
Score: 0.884194136

Rank 5:
Description: LUNCH BAG CARS BLUE
Score: 0.859859109